USE ROLE CURSO_DATA_ENGINEERING;
USE WAREHOUSE WH_CURSO_DATA_ENGINEERING;
USE DEV_CURSO_BRZ_DB_ALUMNO_29;

create or replace schema bronze
CLONE CURSO_DATA_ENGINEERING_2026.BRONZE; 

CREATE OR REPLACE SCHEMA SILVER;

-- SILVER

--  ORDERS
CREATE OR REPLACE TABLE SILVER.ORDERS (
    ORDER_ID VARCHAR(50),
    SHIPPING_SERVICE VARCHAR(20),
    SHIPPING_COST FLOAT,
    ADDRESS_ID VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ,
    Promo_Name VARCHAR(50),
    ESTIMATED_DELIVERY_AT TIMESTAMP_NTZ,
    ORDER_COST FLOAT,
    USER_ID VARCHAR(50),
    ORDER_TOTAL FLOAT,
    DELIVERED_AT TIMESTAMP_NTZ,
    TRACKING_ID VARCHAR(50),
    STATUS VARCHAR(20),
    Delivery_time_hours INT
);

-- EVENTS
CREATE OR REPLACE TABLE SILVER.EVENTS (
    EVENT_ID VARCHAR(50),
    PAGE_URL VARCHAR(200),
    EVENT_TYPE VARCHAR(50),
    USER_ID VARCHAR(50),
    PRODUCT_ID VARCHAR(50),
    SESSION_ID VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ,
    ORDER_ID VARCHAR(50),
    Hit_number INT
);

-- PRODUCTS
CREATE OR REPLACE TABLE SILVER.PRODUCTS (
    PRODUCT_ID VARCHAR(50),
    PRICE FLOAT,
    NAME VARCHAR(100),
    INVENTORY NUMBER(38,0)
);

-- ADDRESSES
CREATE OR REPLACE TABLE SILVER.ADDRESSES (
    ADDRESS_ID VARCHAR(50),
    ZIPCODE NUMBER(38,0),
    COUNTRY VARCHAR(50),
    ADDRESS VARCHAR(150),
    STATE VARCHAR(50)
);

-- USERS
CREATE OR REPLACE TABLE SILVER.USERS (
    USER_ID VARCHAR(50),
    UPDATED_AT TIMESTAMP_NTZ,
    ADDRESS_ID VARCHAR(50),
    LAST_NAME VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ,
    PHONE_NUMBER VARCHAR(20),
    FIRST_NAME VARCHAR(50),
    EMAIL VARCHAR(100)
);

-- ORDER_ITEMS
CREATE OR REPLACE TABLE SILVER.ORDER_ITEMS (
    ORDER_ID VARCHAR(50),
    PRODUCT_ID VARCHAR(50),
    QUANTITY NUMBER(38,0)
);

-- PROMOS
CREATE OR REPLACE TABLE SILVER.PROMOS (
    PROMO_ID VARCHAR(50),
    DISCOUNT FLOAT,
    STATUS VARCHAR(50)
);

-- USERS
INSERT INTO SILVER.USERS 
SELECT 
    USER_ID::varchar(50),
    UPDATED_AT::timestamp_ntz,
    ADDRESS_ID::varchar(50),
    LAST_NAME::varchar(50),
    CREATED_AT::timestamp_ntz,
    PHONE_NUMBER::varchar(20),
    FIRST_NAME::varchar(50),
    EMAIL::varchar(100)
FROM bronze.users;

-- ORDER_ITEMS
INSERT INTO SILVER.ORDER_ITEMS 
SELECT 
    ORDER_ID::varchar(50),
    PRODUCT_ID::varchar(50),
    QUANTITY::number(38,0)
FROM bronze.order_items;

-- PROMOS
INSERT INTO SILVER.PROMOS 
SELECT 
    PROMO_ID::varchar(50),
    DISCOUNT::float,
    STATUS::varchar(50)
FROM BRONZE.promos;

SELECT * FROM SILVER.PROMOS;
SELECT * FROM SILVER.ORDER_ITEMS;
SELECT * FROM SILVER.USERS;

SELECT * FROM BRONZE.ORDERS;

--Diferencia de horas en las órdenes
SELECT 
    ORDER_ID,
    CREATED_AT,
    DELIVERED_AT,
    DATEDIFF(
        HOUR, 
        TRY_TO_TIMESTAMP(NULLIF(CREATED_AT, 'NULL')),
        TRY_TO_TIMESTAMP(NULLIF(DELIVERED_AT, 'NULL'))
    ) AS DELIVERY_TIME_HOURS
FROM BRONZE.ORDERS;

--Añadir hit number
SELECT
    EVENT_ID,
    SESSION_ID,
    CREATED_AT,
    EVENT_TYPE,
    USER_ID,
    PRODUCT_ID,
    ROW_NUMBER() OVER (
        PARTITION BY SESSION_ID 
        ORDER BY TRY_TO_TIMESTAMP(CREATED_AT)
    ) AS HIT_NUMBER
FROM BRONZE.EVENTS
ORDER BY SESSION_ID, HIT_NUMBER;

--Contar eventos de una sesion
SELECT 
    SESSION_ID,
    COUNT(*) AS TOTAL_EVENTOS
FROM BRONZE.EVENTS
GROUP BY SESSION_ID
ORDER BY TOTAL_EVENTOS DESC;

-- PRODUCTS
INSERT INTO SILVER.PRODUCTS
SELECT
    PRODUCT_ID::varchar(50),
    PRICE::float,
    NAME::varchar(100),
    INVENTORY::number(38,0)
FROM BRONZE.PRODUCTS;

-- ADDRESSES
INSERT INTO SILVER.ADDRESSES
SELECT
    ADDRESS_ID::varchar(50),
    ZIPCODE::number(38,0),
    COUNTRY::varchar(50),
    ADDRESS::varchar(150),
    STATE::varchar(50)
FROM BRONZE.ADDRESSES;

-- ORDERS (con DELIVERY_TIME_HOURS)
INSERT INTO SILVER.ORDERS
SELECT
    ORDER_ID::varchar(50),
    SHIPPING_SERVICE::varchar(20),
    REPLACE(SHIPPING_COST, ',', '.')::float,
    ADDRESS_ID::varchar(50),
    TRY_TO_TIMESTAMP(NULLIF(CREATED_AT, 'NULL')),
    NULLIF(PROMO_ID, 'NULL')::varchar(50),
    TRY_TO_TIMESTAMP(NULLIF(ESTIMATED_DELIVERY_AT, 'NULL')),
    REPLACE(ORDER_COST, ',', '.')::float,
    USER_ID::varchar(50),
    REPLACE(ORDER_TOTAL, ',', '.')::float, 
    TRY_TO_TIMESTAMP(NULLIF(DELIVERED_AT, 'NULL')),
    TRACKING_ID::varchar(50),
    STATUS::varchar(20),
    DATEDIFF(
        HOUR,
        TRY_TO_TIMESTAMP(NULLIF(CREATED_AT, 'NULL')),
        TRY_TO_TIMESTAMP(NULLIF(DELIVERED_AT, 'NULL'))
    )::int
FROM BRONZE.ORDERS;

-- EVENTS (con HIT_NUMBER)
INSERT INTO SILVER.EVENTS
SELECT
    EVENT_ID::varchar(50),
    PAGE_URL::varchar(200),
    EVENT_TYPE::varchar(50),
    USER_ID::varchar(50),
    NULLIF(PRODUCT_ID, 'NULL')::varchar(50),
    SESSION_ID::varchar(50),
    TRY_TO_TIMESTAMP(NULLIF(CREATED_AT, 'NULL')),
    NULLIF(ORDER_ID, 'NULL')::varchar(50),
    ROW_NUMBER() OVER (
        PARTITION BY SESSION_ID
        ORDER BY TRY_TO_TIMESTAMP(CREATED_AT)
    )::int
FROM BRONZE.EVENTS;

SELECT * FROM BRONZE.EVENTS;
select * from bronze.orders;
select * from bronze.promos;

select * from silver.events;
select * from silver.orders;

CREATE OR REPLACE FUNCTION TO_DISCOUNT_PERCENTAGE(DISCOUNT VARCHAR)
RETURNS FLOAT
AS
$$
    ROUND(DISCOUNT::float / 100, 2)
$$;

--====================================================================================================================---

CREATE OR REPLACE PROCEDURE INSERT_PROCEDURE()
    RETURNS VARCHAR
    LANGUAGE SQL
    EXECUTE AS CALLER
AS
BEGIN
    -- Truncado de todas las tablas
    TRUNCATE TABLE DEV_CURSO_BRZ_DB_ALUMNO_29.SILVER.USERS;
    TRUNCATE TABLE DEV_CURSO_BRZ_DB_ALUMNO_29.SILVER.ORDER_ITEMS;
    TRUNCATE TABLE DEV_CURSO_BRZ_DB_ALUMNO_29.SILVER.PROMOS;
    TRUNCATE TABLE DEV_CURSO_BRZ_DB_ALUMNO_29.SILVER.PRODUCTS;
    TRUNCATE TABLE DEV_CURSO_BRZ_DB_ALUMNO_29.SILVER.ADDRESSES;
    TRUNCATE TABLE DEV_CURSO_BRZ_DB_ALUMNO_29.SILVER.ORDERS;
    TRUNCATE TABLE DEV_CURSO_BRZ_DB_ALUMNO_29.SILVER.EVENTS;

    -- USERS
    INSERT INTO SILVER.USERS 
    SELECT 
        USER_ID::varchar(50),
        UPDATED_AT::timestamp_ntz,
        ADDRESS_ID::varchar(50),
        LAST_NAME::varchar(50),
        CREATED_AT::timestamp_ntz,
        PHONE_NUMBER::varchar(20),
        FIRST_NAME::varchar(50),
        EMAIL::varchar(100)
    FROM BRONZE.USERS;

    -- ORDER_ITEMS
    INSERT INTO SILVER.ORDER_ITEMS 
    SELECT 
        ORDER_ID::varchar(50),
        PRODUCT_ID::varchar(50),
        QUANTITY::number(38,0)
    FROM BRONZE.ORDER_ITEMS;

    -- PROMOS (usando la función TO_DISCOUNT_PERCENTAGE)
    INSERT INTO SILVER.PROMOS 
    SELECT 
        PROMO_ID::varchar(50),
        TO_DISCOUNT_PERCENTAGE(DISCOUNT),
        STATUS::varchar(50)
    FROM BRONZE.PROMOS;

    -- PRODUCTS
    INSERT INTO SILVER.PRODUCTS
    SELECT
        PRODUCT_ID::varchar(50),
        REPLACE(PRICE, ',', '.')::float,
        NAME::varchar(100),
        INVENTORY::number(38,0)
    FROM BRONZE.PRODUCTS;

    -- ADDRESSES
    INSERT INTO SILVER.ADDRESSES
    SELECT
        ADDRESS_ID::varchar(50),
        ZIPCODE::number(38,0),
        COUNTRY::varchar(50),
        ADDRESS::varchar(150),
        STATE::varchar(50)
    FROM BRONZE.ADDRESSES;

    -- ORDERS
    INSERT INTO SILVER.ORDERS
    SELECT
        ORDER_ID::varchar(50),
        SHIPPING_SERVICE::varchar(20),
        REPLACE(SHIPPING_COST, ',', '.')::float,
        ADDRESS_ID::varchar(50),
        TRY_TO_TIMESTAMP(NULLIF(CREATED_AT, 'NULL')),
        NULLIF(PROMO_ID, 'NULL')::varchar(50),
        TRY_TO_TIMESTAMP(NULLIF(ESTIMATED_DELIVERY_AT, 'NULL')),
        REPLACE(ORDER_COST, ',', '.')::float,
        USER_ID::varchar(50),
        REPLACE(ORDER_TOTAL, ',', '.')::float,
        TRY_TO_TIMESTAMP(NULLIF(DELIVERED_AT, 'NULL')),
        TRACKING_ID::varchar(50),
        STATUS::varchar(20),
        DATEDIFF(
            HOUR,
            TRY_TO_TIMESTAMP(NULLIF(CREATED_AT, 'NULL')),
            TRY_TO_TIMESTAMP(NULLIF(DELIVERED_AT, 'NULL'))
        )::int
    FROM BRONZE.ORDERS;

    -- EVENTS
    INSERT INTO SILVER.EVENTS
    SELECT
        EVENT_ID::varchar(50),
        PAGE_URL::varchar(200),
        EVENT_TYPE::varchar(50),
        USER_ID::varchar(50),
        NULLIF(PRODUCT_ID, 'NULL')::varchar(50),
        SESSION_ID::varchar(50),
        TRY_TO_TIMESTAMP(NULLIF(CREATED_AT, 'NULL')),
        NULLIF(ORDER_ID, 'NULL')::varchar(50),
        ROW_NUMBER() OVER (
            PARTITION BY SESSION_ID
            ORDER BY TRY_TO_TIMESTAMP(CREATED_AT)
        )::int
    FROM BRONZE.EVENTS;

    RETURN 'Insertado con éxito máquina';
END;

CALL INSERT_PROCEDURE();

SELECT COUNT(*) FROM SILVER.USERS;
SELECT COUNT(*) FROM SILVER.ORDER_ITEMS;
SELECT COUNT(*) FROM SILVER.PROMOS;
SELECT COUNT(*) FROM SILVER.PRODUCTS;
SELECT COUNT(*) FROM SILVER.ADDRESSES;
SELECT COUNT(*) FROM SILVER.ORDERS;
SELECT COUNT(*) FROM SILVER.EVENTS;

