USE ROLE CURSO_DATA_ENGINEERING;
USE WAREHOUSE WH_CURSO_DATA_ENGINEERING;
USE DEV_CURSO_BRZ_DB_ALUMNO_29;

CREATE OR REPLACE SCHEMA GOLD;

create or replace schema silver
CLONE CURSO_DATA_ENGINEERING_2026.silver; 


--### Caso de uso 1: SESSION DETAILS

CREATE OR REPLACE TABLE GOLD.session_details (
    session_id VARCHAR(50),
    Finish_with_Order BOOLEAN,
    Num_Eventos INT,
    Session_duration_minutes INT
);

select * from silver.events;
select * from silver.orders;

-- Primero validamos la SELECT
SELECT 
    session_id,
    CASE WHEN MAX(order_id) IS NULL THEN FALSE ELSE TRUE END,
    MAX(hit_number),
    TIMESTAMPDIFF(MINUTE,MIN(created_at),MAX(created_at))
FROM SILVER.events 
GROUP BY session_id;


INSERT INTO GOLD.SESSION_DETAILS
SELECT 
    session_id,
    CASE WHEN MAX(order_id) IS NULL THEN FALSE ELSE TRUE END,
    MAX(hit_number),
    TIMESTAMPDIFF(MINUTE,MIN(created_at),MAX(created_at))
FROM SILVER.events 
GROUP BY session_id;

select * from gold.session_details;


--### Caso de uso 2: STATE ANALISIS

-- STATE ANALYSIS
CREATE OR REPLACE TABLE GOLD.GENERAL_STATE_ANALYSIS (
    state VARCHAR(50),
    TOTAL_ORDER_COSTS FLOAT,
    NUMBER_OF_ORDERS INT,
    NUMBER_OF_USERS INT,
    SHIPPING_COST_PERCENTAGE FLOAT,
    Main_shipping_service VARCHAR(50)
);




select * from
silver.ORDERS;

select * from silver.ADDRESSES;

-- Validamos la SELECT
SELECT
    A.STATE,
    SUM(O.ORDER_COST) AS TOTAL_ORDER_COSTS,
    COUNT(O.ORDER_ID) AS NUMBER_OF_ORDERS,
    COUNT(DISTINCT O.USER_ID) AS NUMBER_OF_USERS,
    SUM(O.SHIPPING_COST) / SUM(O.ORDER_COST) * 100 AS SHIPPING_COST_PERCENTAGE,
    MODE(O.SHIPPING_SERVICE) AS MAIN_SHIPPING_SERVICE
FROM SILVER.ORDERS O
JOIN SILVER.ADDRESSES A ON O.ADDRESS_ID = A.ADDRESS_ID
GROUP BY A.STATE
ORDER BY A.STATE;

INSERT INTO GOLD.general_state_analysis
SELECT
    A.STATE,
    SUM(O.ORDER_COST) AS TOTAL_ORDER_COSTS,
    COUNT(O.ORDER_ID) AS NUMBER_OF_ORDERS,
    COUNT(DISTINCT O.USER_ID) AS NUMBER_OF_USERS,
    SUM(O.SHIPPING_COST) / SUM(O.ORDER_COST) * 100 AS SHIPPING_COST_PERCENTAGE,
    MODE(O.SHIPPING_SERVICE) AS MAIN_SHIPPING_SERVICE
FROM SILVER.ORDERS O
JOIN SILVER.ADDRESSES A ON O.ADDRESS_ID = A.ADDRESS_ID
GROUP BY A.STATE
ORDER BY A.STATE;

select * from gold.general_state_analysis;


--INGESTA DE DATOS

-- PROCEDURE GOLD
CREATE OR REPLACE PROCEDURE INSERT_GOLD_PROCEDURE()
    RETURNS VARCHAR
    LANGUAGE SQL
    EXECUTE AS CALLER
AS
BEGIN
    TRUNCATE TABLE DEV_CURSO_BRZ_DB_ALUMNO_29.GOLD.SESSION_DETAILS;
    TRUNCATE TABLE DEV_CURSO_BRZ_DB_ALUMNO_29.GOLD.GENERAL_STATE_ANALYSIS;

    INSERT INTO GOLD.SESSION_DETAILS
    SELECT
        SESSION_ID,
        BOOLOR_AGG(ORDER_ID IS NOT NULL),
        MAX(HIT_NUMBER),
        DATEDIFF(MINUTE, MIN(CREATED_AT), MAX(CREATED_AT))
    FROM SILVER.EVENTS
    GROUP BY SESSION_ID;

    INSERT INTO GOLD.GENERAL_STATE_ANALYSIS
    SELECT
        A.STATE,
        SUM(O.ORDER_COST),
        COUNT(O.ORDER_ID),
        COUNT(DISTINCT O.USER_ID),
        SUM(O.SHIPPING_COST) / SUM(O.ORDER_COST) * 100,
        MODE(O.SHIPPING_SERVICE)
    FROM SILVER.ORDERS O
    JOIN SILVER.ADDRESSES A ON O.ADDRESS_ID = A.ADDRESS_ID
    GROUP BY A.STATE;

    RETURN 'Gold insertado con éxito máquina';
END;

CALL INSERT_GOLD_PROCEDURE();

-- Ingestar ORDERS desde JSON
-- Primero creamos el file format
CREATE OR REPLACE FILE FORMAT DEV_CURSO_BRZ_DB_ALUMNO_29.PUBLIC.JSON_FORMAT
    TYPE = 'JSON'
    STRIP_OUTER_ARRAY = TRUE;

-- Ingestar ORDERS desde JSON
INSERT INTO BRONZE.ORDERS
SELECT
    f.value:ORDER_ID::VARCHAR(256),
    f.value:SHIPPING_SERVICE::VARCHAR(256),
    f.value:SHIPPING_COST::VARCHAR(256),
    f.value:ADDRESS_ID::VARCHAR(256),
    f.value:CREATED_AT::VARCHAR(256),
    f.value:PROMO_ID::VARCHAR(256),
    f.value:ESTIMATED_DELIVERY_AT::VARCHAR(256),
    f.value:ORDER_COST::VARCHAR(256),
    f.value:USER_ID::VARCHAR(256),
    f.value:ORDER_TOTAL::VARCHAR(256),
    f.value:DELIVERED_AT::VARCHAR(256),
    f.value:TRACKING_ID::VARCHAR(256),
    f.value:STATUS::VARCHAR(256)
FROM @BRONZE.STAGE_JAIME/insert_orders.json.gz
    (FILE_FORMAT => 'PUBLIC.JSON_FORMAT') AS raw_data,
LATERAL FLATTEN(INPUT => raw_data.$1) f;

-- Ingestar ORDER_ITEMS desde JSON
INSERT INTO BRONZE.ORDER_ITEMS
SELECT
    f.value:ORDER_ID::VARCHAR(256),
    f.value:PRODUCT_ID::VARCHAR(256),
    f.value:QUANTITY::VARCHAR(256)
FROM @BRONZE.STAGE_JAIME/insert_order_items.json
    (FILE_FORMAT => 'PUBLIC.JSON_FORMAT') AS raw_data,
LATERAL FLATTEN(INPUT => raw_data.$1) f;

select* from bronze.order_items;