USE ROLE CURSO_DATA_ENGINEERING;
USE WAREHOUSE WH_CURSO_DATA_ENGINEERING;
USE DEV_CURSO_DB_ALUMNO_29;

-- GOLD: Tabla y procedure
CREATE OR REPLACE TABLE GOLD.ORDERS_STATUS_DATE AS (
    SELECT 
        TO_DATE(CREATED_AT) AS FECHA_CREACION_PEDIDO,
        STATUS,
        COUNT(DISTINCT ORDER_ID) AS NUM_PEDIDOS
    FROM SILVER.ORDERS
    GROUP BY TO_DATE(CREATED_AT), STATUS
    ORDER BY 1 DESC
);

CREATE OR REPLACE PROCEDURE GOLD.UPDATE_GOLD_ORDERS_STATUS()
RETURNS VARCHAR
LANGUAGE SQL
AS
BEGIN
    CREATE OR REPLACE TABLE DEV_CURSO_DB_ALUMNO_29.GOLD.ORDERS_STATUS_DATE AS (
        SELECT 
            TO_DATE(CREATED_AT) AS FECHA_CREACION_PEDIDO,
            STATUS,
            COUNT(DISTINCT ORDER_ID) AS NUM_PEDIDOS
        FROM DEV_CURSO_DB_ALUMNO_29.SILVER.ORDERS
        GROUP BY TO_DATE(CREATED_AT), STATUS
        ORDER BY 1 DESC
    );
    RETURN 'Tabla ORDERS_STATUS_DATE actualizada con éxito';
END;

-- PASO 1: Stream (sobre la tabla COMÚN, no la tuya)
CREATE OR REPLACE STREAM BRONZE.ORDERS_STREAM_29
ON TABLE BRONZE.ORDERS_HIST
APPEND_ONLY = TRUE;

SHOW STREAMS IN SCHEMA DEV_CURSO_DB_ALUMNO_29.BRONZE;

-- PASO 2: Root task con MERGE
CREATE OR REPLACE TASK DEV_CURSO_DB_ALUMNO_29.BRONZE.UPDATE_SILVER_ORDERS
    WAREHOUSE = WH_CURSO_DATA_ENGINEERING
    SCHEDULE = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('DEV_CURSO_DB_ALUMNO_29.BRONZE.ORDERS_STREAM')
AS
    MERGE INTO DEV_CURSO_DB_ALUMNO_29.SILVER.ORDERS t
    USING (
        SELECT * FROM DEV_CURSO_DB_ALUMNO_29.BRONZE.ORDERS_STREAM
    ) s ON t.ORDER_ID = s.ORDER_ID

    WHEN MATCHED THEN UPDATE SET
        t.SHIPPING_SERVICE      = s.SHIPPING_SERVICE::VARCHAR(20),
        t.SHIPPING_COST         = REPLACE(s.SHIPPING_COST, ',', '.')::DECIMAL,
        t.ADDRESS_ID            = s.ADDRESS_ID::VARCHAR(50),
        t.CREATED_AT            = s.CREATED_AT::TIMESTAMP_NTZ,
        t.PROMO_NAME            = IFNULL(s.PROMO_ID, 'N/A'),
        t.ESTIMATED_DELIVERY_AT = s.ESTIMATED_DELIVERY_AT::TIMESTAMP_NTZ,
        t.ORDER_COST            = REPLACE(s.ORDER_COST, ',', '.')::DECIMAL,
        t.USER_ID               = s.USER_ID::VARCHAR(50),
        t.ORDER_TOTAL           = REPLACE(s.ORDER_TOTAL, ',', '.')::DECIMAL,
        t.DELIVERED_AT          = s.DELIVERED_AT::TIMESTAMP_NTZ,
        t.TRACKING_ID           = s.TRACKING_ID::VARCHAR(50),
        t.STATUS                = s.STATUS::VARCHAR(20),
        t.DELIVERY_TIME_HOURS   = TIMESTAMPDIFF(HOUR, s.CREATED_AT, s.DELIVERED_AT)

    WHEN NOT MATCHED THEN INSERT (
        ORDER_ID, SHIPPING_SERVICE, SHIPPING_COST, ADDRESS_ID, CREATED_AT,
        PROMO_NAME, ESTIMATED_DELIVERY_AT, ORDER_COST, USER_ID, ORDER_TOTAL,
        DELIVERED_AT, TRACKING_ID, STATUS, DELIVERY_TIME_HOURS
    ) VALUES (
        s.ORDER_ID::VARCHAR(100),
        s.SHIPPING_SERVICE::VARCHAR(20),
        REPLACE(s.SHIPPING_COST, ',', '.')::DECIMAL,
        s.ADDRESS_ID::VARCHAR(50),
        s.CREATED_AT::TIMESTAMP_NTZ,
        IFNULL(s.PROMO_ID, 'N/A'),
        s.ESTIMATED_DELIVERY_AT::TIMESTAMP_NTZ,
        REPLACE(s.ORDER_COST, ',', '.')::DECIMAL,
        s.USER_ID::VARCHAR(50),
        REPLACE(s.ORDER_TOTAL, ',', '.')::DECIMAL,
        s.DELIVERED_AT::TIMESTAMP_NTZ,
        s.TRACKING_ID::VARCHAR(50),
        s.STATUS::VARCHAR(20),
        TIMESTAMPDIFF(HOUR, s.CREATED_AT, s.DELIVERED_AT)
    );

-- Activar la root task
ALTER TASK DEV_CURSO_DB_ALUMNO_29.BRONZE.UPDATE_SILVER_ORDERS RESUME;

-- Verificaciones
SHOW TASKS IN SCHEMA DEV_CURSO_DB_ALUMNO_29.BRONZE;
SELECT * FROM DEV_CURSO_DB_ALUMNO_29.SILVER.ORDERS;
SELECT * FROM DEV_CURSO_DB_ALUMNO_29.GOLD.ORDERS_STATUS_DATE;

-- PASO 3: Tarea Hija (Se ejecuta al terminar UPDATE_SILVER_ORDERS)
CREATE OR REPLACE TASK BRONZE.TASK_HIJA
    WAREHOUSE = WH_CURSO_DATA_ENGINEERING
    AFTER BRONZE.UPDATE_SILVER_ORDERS
AS
    CALL DEV_CURSO_DB_ALUMNO_29.GOLD.UPDATE_GOLD_ORDERS_STATUS();

-- PASO 4: Activar Tareas (Primero HIJA, luego RAÍZ)
ALTER TASK BRONZE.TASK_HIJA RESUME;
ALTER TASK BRONZE.UPDATE_SILVER_ORDERS RESUME;

-- Verificar que ambas están 'Started'
SHOW TASKS IN SCHEMA DEV_CURSO_DB_ALUMNO_29.BRONZE;

--Comprobar el historial de tareas
SELECT 
    NAME,
    STATE,
    SCHEDULED_TIME,
    QUERY_START_TIME,
    COMPLETED_TIME,
    ERROR_MESSAGE
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(
    SCHEDULED_TIME_RANGE_START => DATEADD('hour', -1, CURRENT_TIMESTAMP()),
    RESULT_LIMIT => 10
))
WHERE NAME IN ('UPDATE_SILVER_ORDERS', 'TASK_HIJA')
ORDER BY SCHEDULED_TIME DESC;


ALTER TASK BRONZE.TASK_HIJA SUSPEND;
ALTER TASK BRONZE.UPDATE_SILVER_ORDERS SUSPEND;

DROP TASK BRONZE.TASK_HIJA;
DROP TASK BRONZE.UPDATE_SILVER_ORDERS;