openapi: 3.0.0
info:
  title: Api Jaime
  version: "1.0.0"
  description: Descripción de la Api Jaime
  contact:
    name: Jaime Molina Granados
    email: jaimemg1312@gmail.com

servers:
  - url: https://api.tuservidor.com/v1
    description: Servidor de producción
  - url: http://localhost:8080
    description: Servidor local

tags:
  - name: Usuarios
    description: Operaciones con usuarios

paths:
  /usuarios:
    get:
      tags:
        - Usuarios
      summary: Obtiene lista de usuarios
      parameters:
        - name: limite
          in: query
          schema:
            type: integer
          description: Número máximo de resultados
      responses:
        "200":
          description: Lista de usuarios encontrada
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Usuario"

components:
  schemas:
    Usuario:
      type: object
      required:
        - nombre
        - email
      properties:
        id:
          type: integer
          readOnly: true
        nombre:
          type: string
          example: "Juan Pérez"
        email:
          type: string
          format: email
          example: "juan@email.com"
