USE ROLE CURSO_DATA_ENGINEERING;
USE WAREHOUSE WH_CURSO_DATA_ENGINEERING;
USE DEV_CURSO_BRZ_DB_ALUMNO_29.BRONZE;

--Creamos la base de datos
create or replace database dev_curso_brz_db_alumno_29;

--Creamos la parte de bronce
create or replace schema bronze;
-- Create Events --
CREATE TABLE EVENTS(
	EVENT_ID VARCHAR(256),
	PAGE_URL VARCHAR(256),
	EVENT_TYPE VARCHAR(256),
	USER_ID VARCHAR(256),
	PRODUCT_ID VARCHAR(256),
	SESSION_ID VARCHAR(256),
	CREATED_AT VARCHAR(256),
	ORDER_ID VARCHAR(256)
);

-- Create ORDER_ITEMS --
CREATE TABLE ORDER_ITEMS(
	ORDER_ID VARCHAR(256),
	PRODUCT_ID VARCHAR(256),
	QUANTITY VARCHAR(256)
);

-- Create ORDERS --
CREATE TABLE ORDERS(
	ORDER_ID VARCHAR(256),
	SHIPPING_SERVICE VARCHAR(256),
	SHIPPING_COST VARCHAR(256),
	ADDRESS_ID VARCHAR(256),
	CREATED_AT VARCHAR(256),
	PROMO_ID VARCHAR(256),
	ESTIMATED_DELIVERY_AT VARCHAR(256),
	ORDER_COST VARCHAR(256),
	USER_ID VARCHAR(256),
	ORDER_TOTAL VARCHAR(256),
	DELIVERED_AT VARCHAR(256),
	TRACKING_ID VARCHAR(256),
	STATUS VARCHAR(256)
);

-- Create PRODUCTS --
CREATE TABLE PRODUCTS(
	PRODUCT_ID VARCHAR(256),
	PRICE VARCHAR(256),
	NAME VARCHAR(256),
	INVENTORY VARCHAR(256)
);

-- Create PROMOS --
CREATE TABLE PROMOS(
	PROMO_ID VARCHAR(256),
	DISCOUNT VARCHAR(256),
	STATUS VARCHAR(256)
);

-- Create Users --
CREATE TABLE USERS(
	USER_ID VARCHAR(256),
	UPDATED_AT VARCHAR(256),
	ADDRESS_ID VARCHAR(256),
	LAST_NAME VARCHAR(256),
	CREATED_AT VARCHAR(256),
	PHONE_NUMBER VARCHAR(256),
	TOTAL_ORDERS VARCHAR(256),
	FIRST_NAME VARCHAR(256),
	EMAIL VARCHAR(256)
);DEV_CURSO_BRZ_DB_ALUMNO_29.BRONZE;

CREATE OR REPLACE TABLE ADDRESSES (
    ADDRESS_ID VARCHAR(256),
    ZIPCODE VARCHAR(256),
    COUNTRY VARCHAR(256),
    ADDRESS VARCHAR(256),
    STATE VARCHAR(256)
);

select * from CURSO_DATA_ENGINEERING_2026.BRONZE.;

-- Subir el archivo local al stage interno de la tabla
PUT file:CURSO_DATA_ENGINEERING_2026.BRONZE. @stage_jaime 

AUTO_COMPRESS=TRUE 
OVERWRITE=TRUE;

COPY INTO ORDERS
FROM @CURSO_DATA_ENGINEERING_2026.BRONZE.LANDING_STG/orders.csv
FILE_FORMAT = (
    TYPE = CSV,
    FIELD_DELIMITER = ';',
    SKIP_HEADER = 1,
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);

COPY INTO EVENTS
FROM @CURSO_DATA_ENGINEERING_2026.BRONZE.LANDING_STG/events.csv
FILE_FORMAT = (
    TYPE = CSV,
    FIELD_DELIMITER = ';',
    SKIP_HEADER = 1,
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);

COPY INTO ORDER_ITEMS
FROM @CURSO_DATA_ENGINEERING_2026.BRONZE.LANDING_STG/order_items.csv
FILE_FORMAT = (
    TYPE = CSV,
    FIELD_DELIMITER = ';',
    SKIP_HEADER = 1,
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);

COPY INTO USERS
FROM @CURSO_DATA_ENGINEERING_2026.BRONZE.LANDING_STG/users.csv
FILE_FORMAT = (
    TYPE = CSV,
    FIELD_DELIMITER = ';',
    SKIP_HEADER = 1,
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);

COPY INTO ADDRESSES
FROM @CURSO_DATA_ENGINEERING_2026.BRONZE.LANDING_STG/addresses.csv
FILE_FORMAT = (
    TYPE = CSV,
    FIELD_DELIMITER = ';',
    SKIP_HEADER = 1,
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);

--Crear stage donde subir los archivos

CREATE OR REPLACE STAGE stage_jaime;

PUT file://C:\Users\de29\Desktop\civica-data-engineering-curso-main\Dia1\users.csv @stage_jaime
AUTO_COMPRESS=TRUE OVERWRITE=TRUE;


COPY INTO products
FROM @DEV_CURSO_BRZ_DB_ALUMNO_29.BRONZE.STAGE_JAIME/products.csv
FILE_FORMAT = (
    TYPE = CSV,
    FIELD_DELIMITER = ',',
    SKIP_HEADER = 1,
    FIELD_OPTIONALLY_ENCLOSED_BY = '"',
    ENCODING = 'UTF8'
);


COPY INTO promos
FROM @DEV_CURSO_BRZ_DB_ALUMNO_29.BRONZE.STAGE_JAIME/promos.csv
FILE_FORMAT = (
    TYPE = CSV,
    FIELD_DELIMITER = ',',
    SKIP_HEADER = 1,
    ENCODING = 'UTF8'
);
