Search.appendIndex(
    [
                {
            "fqsen": "\\Usuario",
            "name": "Usuario",
            "summary": "Usuario",
            "url": "classes/Usuario.html"
        },                {
            "fqsen": "\\Usuario\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020de\u0020la\u0020clase\u0020Usuario",
            "url": "classes/Usuario.html#method___construct"
        },                {
            "fqsen": "\\Usuario\u003A\u003AgetNombre\u0028\u0029",
            "name": "getNombre",
            "summary": "Obtiene\u0020el\u0020nombre\u0020del\u0020usuario",
            "url": "classes/Usuario.html#method_getNombre"
        },                {
            "fqsen": "\\Usuario\u003A\u003A\u0024id",
            "name": "id",
            "summary": "ID\u0020del\u0020usuario",
            "url": "classes/Usuario.html#property_id"
        },                {
            "fqsen": "\\Usuario\u003A\u003A\u0024nombre",
            "name": "nombre",
            "summary": "Nombre\u0020del\u0020usuario",
            "url": "classes/Usuario.html#property_nombre"
        },                {
            "fqsen": "\\Usuario\u003A\u003A\u0024email",
            "name": "email",
            "summary": "Email\u0020del\u0020usuario",
            "url": "classes/Usuario.html#property_email"
        },                {
            "fqsen": "\\Producto",
            "name": "Producto",
            "summary": "Producto",
            "url": "classes/Producto.html"
        },                {
            "fqsen": "\\Producto\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020de\u0020la\u0020clase\u0020Producto",
            "url": "classes/Producto.html#method___construct"
        },                {
            "fqsen": "\\Producto\u003A\u003AgetPrecio\u0028\u0029",
            "name": "getPrecio",
            "summary": "Obtiene\u0020el\u0020precio\u0020del\u0020producto",
            "url": "classes/Producto.html#method_getPrecio"
        },                {
            "fqsen": "\\Producto\u003A\u003A\u0024nombre",
            "name": "nombre",
            "summary": "Nombre\u0020del\u0020producto",
            "url": "classes/Producto.html#property_nombre"
        },                {
            "fqsen": "\\Producto\u003A\u003A\u0024precio",
            "name": "precio",
            "summary": "Precio\u0020del\u0020producto",
            "url": "classes/Producto.html#property_precio"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
